[package]
name = "http-server"
version = "0.1.0"
authors = ["mt-empty"]
edition = "2021"
rust-version = "1.80"

[dependencies]
flate2 = "1.0.35"                                # compression
strum = "0.26"
strum_macros = "0.26"
anyhow = "1.0"